import Foundation

/// Translate application chrome only. User documents/transcripts/model prose are not dictionary keys.
/// Raw protocol/status strings remain stable for diagnostics and persisted V1 data.
enum L10n {
    static func text(_ text: String, language: AppLanguage) -> String {
        guard language.usesChinese else { return text }
        if let value = chinese[text] { return value }
        for (prefix, translated) in [("Indexing ", "正在索引 "), ("Re-indexing ", "正在重建索引 ")] {
            if text.hasPrefix(prefix) { return translated + text.dropFirst(prefix.count) }
        }
        if text.hasPrefix("Listening · ") {
            return text.components(separatedBy: " · ").map { part in
                part.hasSuffix(" ready") ? Self.text(String(part.dropLast(6)), language: language) + " 已就绪" : Self.text(part, language: language)
            }.joined(separator: " · ")
        }
        if text.hasPrefix("Keychain access failed (") {
            let code = text.dropFirst("Keychain access failed ".count).prefix { $0 != "." }
            return "钥匙串访问失败 \(code)。请解锁登录钥匙串，并允许 LiveCopilot 访问所选服务的凭据。"
        }
        for speaker in Speaker.allCases {
            if text == "\(speaker.rawValue): connecting to Live…" { return Self.text(speaker.rawValue, language: language) + "：正在连接实时服务…" }
            if text == "\(speaker.rawValue): disconnected — stop/start listening to retry." { return Self.text(speaker.rawValue, language: language) + "：连接已断开，请重新开始监听。" }
        }
        let rules: [(String, String)] = [
            (#"^Live authentication/access failed \(([a-z_]+)\).*$"#, "实时服务验证失败（$1），请检查密钥与模型权限。"),
            (#"^Live command/session failed \(([a-z_]+)\).*$"#, "实时会话请求失败（$1），请检查模型配置、权限和网络。"),
            (#"^Service authentication/access failed \((\d+)\).*$"#, "服务身份验证或访问失败（$1），请在“服务”中检查密钥与模型权限。"),
            (#"^Service rejected the request \((\d+)\).*$"#, "服务拒绝请求（$1），请检查模型名称和配置。"),
            (#"^Service is temporarily unavailable \((\d+)\).*$"#, "服务暂不可用（$1），请稍后重试。"),
            (#"^Service request failed \(HTTP (\d+)\).*$"#, "服务请求失败（HTTP $1），请检查网络后重试。")
        ]
        for (pattern, replacement) in rules {
            if let regex = try? NSRegularExpression(pattern: pattern), regex.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)) != nil {
                return regex.stringByReplacingMatches(in: text, range: NSRange(text.startIndex..., in: text), withTemplate: replacement)
            }
        }
        return text
    }
    static let chinese: [String: String] = [
        "Ready (re-index failed)": "可用（重建索引失败）",
        "Edit": "编辑", "View": "显示", "Window": "窗口", "Help": "帮助",
        "Undo": "撤销", "Redo": "重做", "Cut": "剪切", "Paste": "粘贴", "Select All": "全选",
        "Close Window": "关闭窗口", "Minimize": "最小化", "Zoom": "缩放", "Bring All to Front": "全部置于最前",
        "Hide LiveCopilot": "隐藏 LiveCopilot", "Hide Others": "隐藏其他", "Show All": "全部显示",
        "About LiveCopilot": "关于 LiveCopilot",
        "Screen Recording permission is required. Grant it in System Settings → Privacy & Security → Screen Recording, then reopen LiveCopilot.": "需要屏幕录制权限，请在系统设置 → 隐私与安全性 → 屏幕录制中允许 LiveCopilot，然后重新打开应用。",
        "Possible question forming": "问题形成中",
        "Already handled": "已处理过此问题",
        "User has already answered": "用户已回答",
        "Waiting for complete context": "等待完整上下文",
        "Live startup timed out. Check network and model access.": "实时服务启动超时，请检查网络和模型权限。",
        "Live disconnected. Reconnecting if possible; manual text queries remain available.": "实时服务已断开，将尝试重新连接；仍可直接输入问题。",
        "Live upload failed. Check network connection.": "实时音频上传失败，请检查网络。",
        "Live authentication/access failed. Check the key and model access.": "实时服务验证失败，请检查密钥与模型权限。",
        "Live connection failed. Check your network.": "实时服务连接失败，请检查网络。",
        "Microphone device configuration changed. Stop/start listening to use the current device.": "麦克风配置已改变，请重新开始监听以使用当前设备。",
        "Microphone permission denied. Enable LiveCopilot in System Settings → Privacy & Security → Microphone.": "未获麦克风权限，请在系统设置 → 隐私与安全性 → 麦克风中允许 LiveCopilot。",
        "No microphone input available.": "没有可用的麦克风输入。",
        "Could not delete session history. Check disk permissions.": "无法删除会话记录，请检查磁盘权限。",
        "Cannot access local session storage.": "无法访问本地会话存储。",
        "Session history could not be saved. Check available disk space and permissions.": "会话记录无法保存，请检查可用磁盘空间和权限。",
        "Choose a regular document smaller than 50 MB.": "请选择小于 50 MB 的普通文档文件。",
        "PDF is unreadable or password protected.": "PDF 无法读取，或受密码保护。",
        "Save this text document as UTF-8 or UTF-16 and retry.": "请将文本文档保存为 UTF-8 或 UTF-16 后重试。",
        "Supported documents: PDF, Markdown, TXT and DOCX.": "支持的文档格式：PDF、Markdown、TXT、DOCX。",
        "No extractable text. Scanned PDFs need OCR before import.": "没有可提取的文字，扫描版 PDF 请先进行 OCR 识别。",
        "Cannot open local knowledge database.": "无法打开本地知识库。",
        "Cannot initialize SQLite/FTS5 knowledge database.": "无法初始化本地 SQLite/FTS5 知识库。",
        "Local knowledge database operation failed. Check disk space and access permissions.": "本地知识库操作失败，请检查磁盘空间和权限。",
        "Invalid embedding response; the previous index was preserved.": "向量响应无效，原有索引已保留。",
        "Document exceeds the V1 limit of 4,000 chunks; split it into smaller documents.": "文档超出 4,000 个片段的限制，请拆分为较小文档。",
        "Embedding API returned an incomplete batch.": "向量 API 返回的数据批次不完整。",
        "General": "通用",
        "Services": "服务",
        "Knowledge": "知识库",
        "Shortcuts": "快捷键",
        "Interface language": "界面语言",
        "Follow system": "跟随系统",
        "Changes apply immediately. Answers follow the language of your question.": "立即生效；回答仍跟随提问的语言。",
        "Window background": "窗口底色",
        "Translucent glass": "半透明毛玻璃",
        "Soft frosted": "微透磨砂",
        "Solid white": "纯白底色",
        "Translucent glass lets more of your desktop show through.": "半透明毛玻璃保留更多桌面背景层次。",
        "Soft frosted keeps a hint of the background with a light veil for clearer text.": "微透磨砂增加柔和浅色遮罩，保留少量背景层次，文字更清晰。",
        "Solid white keeps dark text readable over any wallpaper.": "纯白底色搭配深色文字，不受桌面壁纸影响。",
        "Language & appearance": "语言与外观",
        "Operating mode": "使用模式",
        "Scenario": "场景",
        "Remote Meeting": "远程会议",
        "In-Person / Defense": "现场交流／答辩",
        "Interview": "面试",
        "Meeting": "会议",
        "Academic Defense": "学术答辩",
        "Conversation": "对话",
        "Stop listening to change mode or scenario.": "请先停止监听，再更改模式或场景。",
        "Automatic suggestions for meaningful questions": "识别完整问题后自动提供建议",
        "Capture exclusion": "截图与共享排除",
        "Hide overlay from screenshots and screen sharing": "在截图和屏幕共享中隐藏悬浮窗",
        "Turn this off to capture the overlay. Settings and history can always be captured. Exclusion depends on macOS and your capture app.": "关闭后可截取悬浮窗。设置和历史页始终允许截图；隐藏效果取决于 macOS 和具体捕获软件。",
        "Drag any edge or corner to resize": "拖动任意边缘或角落调整大小",
        "Service role": "服务用途",
        "Live service": "实时服务",
        "Analysis service": "分析服务",
        "Live conversation uses GPT-Live-1. Knowledge indexing and query embeddings also use this OpenAI credential.": "实时对话使用 GPT-Live-1。知识库索引及查询向量也使用此 OpenAI 凭据。",
        "Live model": "实时模型",
        "Embedding model": "向量模型",
        "Models": "模型",
        "After changing the embedding model, re-index documents. Keyword retrieval remains available for older indexes.": "更换向量模型后请重建文档索引；旧索引仍可进行关键词检索。",
        "Provider": "服务商",
        "Use Live service's OpenAI": "沿用实时服务的 OpenAI",
        "OpenAI · separate key": "OpenAI（独立密钥）",
        "OpenAI-compatible": "OpenAI 兼容服务",
        "This service combines the question, conversation and retrieved evidence into an answer. Live audio stays with OpenAI.": "此服务结合问题、对话和检索证据生成回答。实时音频仍由 OpenAI 处理。",
        "Using the Live service credential.": "正在沿用实时服务的凭据。",
        "Manage Live service": "管理实时服务",
        "Reasoning model": "分析模型",
        "Reasoning effort": "推理强度",
        "Model default": "模型默认",
        "Low (faster)": "低（更快）",
        "Medium": "中",
        "High": "高",
        "Maximum": "最高",
        "Off": "关闭",
        "Changes apply to the next answer. Existing knowledge vectors do not need re-indexing when you change only the analysis model.": "更改从下一次回答起生效。只更换分析模型，无需重建知识库向量。",
        "API Base URL": "API 基础地址",
        "API path": "API 路径",
        "Connection": "连接配置",
        "Save connection": "保存连接",
        "Use an HTTPS service supporting streamed Chat Completions. The base URL and path are joined; include /v1 only once.": "使用支持 Chat Completions 流式接口的 HTTPS 服务。基础地址与路径会拼接，/v1 只需填写一次。",
        "Save the service address before configuring its key.": "先保存服务地址，再配置该地址的密钥。",
        "Connection saved. Credentials are scoped to this endpoint.": "连接已保存。密钥仅用于这个 API 地址。",
        "Enter an analysis model name in Services.": "请在“服务”中填写分析模型名称。",
        "Enter an HTTPS base URL and API path without credentials, query parameters or fragments.": "请填写 HTTPS 基础地址和 API 路径，不要在地址中包含密钥、用户名、查询参数或片段。",
        "Invalid analysis service URL.": "分析服务地址无效。",
        "Local knowledge base": "本地知识库",
        "Import documents…": "导入文档…",
        "PDF, Markdown, TXT and DOCX · original copies remain local. Indexing sends extracted text to OpenAI.": "支持 PDF、Markdown、TXT、DOCX。原件副本保留在本机；索引时会将提取的文本发送给 OpenAI。",
        "Evidence chunks": "检索证据片段数",
        "chunks": "片段",
        "chunk": "片段",
        "Ready": "就绪",
        "Indexing": "正在索引",
        "Failed": "失败",
        "Re-index": "重建索引",
        "Show local copy": "显示本地副本",
        "Delete": "删除",
        "Import a document to ground answers in your own evidence.": "导入文档后，回答即可引用你的资料。",
        "Global shortcuts": "全局快捷键",
        "Reset": "重置",
        "⌥H shows/hides the overlay. Click the text box to type; Return submits a question even when listening is off.": "⌥H 显示／隐藏悬浮窗。点击输入框即可打字，按回车提交；无需开启监听。",
        "Reply": "回答建议",
        "Recap": "总结",
        "Follow-up": "追问",
        "Mock credential": "模拟凭据",
        "Checking Keychain…": "正在读取钥匙串…",
        "API key configured": "API Key 已配置",
        "API key not configured": "尚未配置 API Key",
        "Key hidden": "密钥已隐藏",
        "Credential ready. Its contents are never displayed here.": "凭据已就绪，密钥内容不会显示在界面中。",
        "Enter a replacement key": "输入新的密钥以替换",
        "Enter a key to save in Keychain": "输入密钥，安全保存到钥匙串",
        "Save Key": "保存密钥",
        "Replace key…": "更换密钥…",
        "Check Keychain": "检查钥匙串",
        "Remove": "移除",
        "Cancel": "取消",
        "Uses your existing LiveCopilot-OpenAI Keychain item. No need to enter it again.": "使用已有的 LiveCopilot-OpenAI 钥匙串项目，无需重复填写。",
        "Remove this service's saved key?": "移除此服务保存的密钥？",
        "Saved key removed.": "已移除保存的密钥。",
        "Saved in macOS Keychain.": "已安全保存到 macOS 钥匙串。",
        "No credential available.": "尚无可用凭据。",
        "Credential available. No API request made.": "凭据已就绪；本次检查未调用 API。",
        "Mock providers — no credential needed.": "模拟模式无需真实凭据。",
        "Checking Keychain… Complete any macOS access prompt locally.": "正在读取钥匙串…请在本机完成 macOS 访问提示。",
        "MOCK — no API calls": "模拟模式 · 不调用 API",
        "MOCK MODE — no API calls": "模拟模式 · 不调用 API",
        "MOCK listening — sample conversation": "模拟监听 · 示例对话",
        "Ready — type a question or start listening": "就绪，可以输入问题或开始监听",
        "Auto": "自动建议",
        "Show/hide conversation": "显示／隐藏对话",
        "Ask anything — listening can be off": "输入问题，无需开启监听",
        "Ask": "提问",
        "Use recent conversation": "附带近期对话",
        "Stop listening": "停止监听",
        "Start listening": "开始监听",
        "Stop Listening": "停止监听",
        "Start Listening": "开始监听",
        "Toggle your microphone in Remote Meeting mode": "开关远程会议模式下的麦克风",
        "Settings and knowledge base": "设置与知识库",
        "Hide (⌥H)": "隐藏（⌥H）",
        "Conversation appears here when listening.": "开启监听后，对话会显示在这里。",
        "Them": "对方",
        "You": "我",
        "Room": "现场",
        "Follow transcript": "跟随最新转写",
        "Retrieving evidence and thinking…": "正在检索证据并分析…",
        "Ask a question below, or use ⌥Space for help with the conversation.": "在下方输入问题，或按 ⌥Space 根据对话获取建议。",
        "Core answer": "核心回答",
        "Key points": "关键要点",
        "Evidence": "文档证据",
        "General context": "通用知识与推理",
        "Watch-outs": "注意事项",
        "Sources": "来源",
        "Sources · retrieved local evidence": "来源 · 本地检索证据",
        "First text": "首字耗时",
        "Copy": "复制",
        "No key available — open Settings to configure Keychain.": "尚无可用密钥，请在设置的“服务”页配置。",
        "Credential not available yet. Unlock Keychain and use Check Keychain in Settings, or save an API key there.": "凭据尚未就绪。请解锁钥匙串并在“服务”页检查或保存密钥。",
        "Starting audio capture…": "正在启动音频采集…",
        "No audio capture source available.": "暂无可用音频输入。",
        "Connecting Live…": "正在连接实时服务…",
        "Listening stopped — manual questions remain available": "已停止监听，仍可直接输入问题",
        "Room mode uses the microphone. Stop listening to disable it.": "现场模式使用麦克风；停止监听即可关闭。",
        "No conversation yet. Type a question below to ask directly.": "尚无对话，请在下方直接输入问题。",
        "Keep a manual question under 8,000 characters.": "问题请控制在 8,000 字符以内。",
        "Semantic retrieval unavailable; using local keyword search.": "向量检索暂不可用，已改用本地关键词检索。",
        "Knowledge database unavailable; answering from general context.": "知识库暂不可用，将根据一般上下文回答。",
        "Indexing complete. Retrieval is local.": "索引完成，检索在本机进行。",
        "Re-indexing complete.": "重建索引完成。",
        "Deleted local document and index.": "已删除本地文档及其索引。",
        "Configure the analysis service API key in Services.": "请在“服务”页配置分析服务的 API Key。",
        "Malformed reasoning stream. Retry this question.": "分析服务返回的流式内容格式异常，请重试。",
        "Analysis service failed. Check its model, key and API limits.": "分析服务请求失败，请检查模型、密钥和 API 限额。",
        "The analysis answer was interrupted or exceeded its limit. Partial text is retained; retry.": "分析回答被中断或超出限额。已有内容已保留，请重试。",
        "Reasoning stream ended without a complete answer. Check the network and retry.": "连接在回答完成前结束，请检查网络后重试。",
        "Reasoning request failed. Check model access, configuration and API limits, then retry.": "分析请求失败，请检查模型权限、配置和 API 限额后重试。",
        "The answer was cut short. Partial text is retained; retry or choose a lower reasoning effort.": "回答被截断，已有内容已保留。请重试或降低推理强度。",
        "Add an OpenAI API key in Settings, or launch with OPENAI_API_KEY.": "请在“服务”页配置 OpenAI API Key，或用 OPENAI_API_KEY 启动。",
        "Service rate or credit limit reached. Check API billing/limits and retry later.": "服务额度或速率已达上限，请检查余额与限额后重试。",
        "OpenAI returned malformed embeddings.": "OpenAI 返回了格式异常的向量数据。",
        "OpenAI returned missing or incompatible embedding vectors.": "OpenAI 返回的向量缺失或不兼容。",
        "Reasoning stream contained an oversized event. Retry this question.": "分析服务的流式事件过大，请重试。",
        "Reasoning stream contained invalid text encoding. Retry this question.": "分析服务返回了无效的文本编码，请重试。",
        "API key cannot be empty.": "API Key 不能为空。",
        "Mute Mic (You)": "关闭麦克风（我）",
        "Unmute Mic (You)": "开启麦克风（我）",
        "Show / Hide Overlay (⌥H)": "显示／隐藏悬浮窗（⌥H）",
        "History…": "历史记录…",
        "Settings…": "设置…",
        "Quit LiveCopilot": "退出 LiveCopilot",
        "LiveCopilot Settings": "LiveCopilot 设置",
        "LiveCopilot — History": "LiveCopilot — 历史记录",
        "Suggest Reply": "生成回答建议",
        "Sessions": "会话记录",
        "No saved sessions yet.\nStop a listening session to save it here.": "暂无会话记录。\n停止监听时会自动保存到这里。",
        "lines": "条",
        "Select a session": "选择一条会话",
        "Press keys…": "按下快捷键…",
        "Record": "录制",
        "Listening": "正在监听",
        "Possible question": "问题形成中",
        "Question ready": "问题已完整",
        "Assistance in progress": "正在生成建议",
        "Follow-up question": "追问",
        "Duplicate question": "重复问题",
        "Already answered": "已回答"
    ]
}

extension SourceChunk {
    func displayLabel(language: AppLanguage) -> String {
        guard language.usesChinese else { return sourceLabel }
        return "\(documentName) · \(page.map { "第 \($0) 页 · " } ?? "")片段 \(ordinal + 1)"
    }
}
